from __future__ import print_function
import sys
sys.path.append('../../../')

from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import SGD
from Utils import Matrix as matrix
from keras.utils import np_utils
import numpy
batch_size = 32

nb_epoch = 20
data_augmentation = True

# input image dimensions
img_rows, img_cols = 32,32
# the CIFAR10 images are RGB
img_channels = 3

# the data, shuffled and split between train and test sets
# (X_train, y_train), (X_test, y_test) = cifar10.load_data()
# (X_train_1, y_train_1), (X_test_1, y_test_1)= cifar10.load_data()


trainFolder = '/home/leovala/databases/Clef2013/TrainSet'
testFolder = '/home/leovala/databases/Clef2013/TestSet'

trainFolder = 'C:\Users\l.valavanis\Desktop\Clef2012\SampleImages - Copy'
testFolder = 'C:\Users\l.valavanis\Desktop\Clef2012\SampleImages - Copy - Copy'

trainFolder = 'C:\Users\l.valavanis\Desktop\Clef2012\TrainSet'
testFolder = 'C:\Users\l.valavanis\Desktop\Clef2012\TestSet'

# (X_train_1, y_train_1), (X_test_1, y_test_1) = mnist.load_data()
[X_train, Y_train, X_test, Y_test,outputClasses] = \
matrix.load_dataset(trainFolder, testFolder,imageSize=(img_rows,img_rows),convertion="RGB")
nb_classes = len(numpy.unique(Y_train))

Y_test = numpy.reshape(Y_test, (len(Y_test), 1))
Y_train = numpy.reshape(Y_train, (len(Y_train), 1))

print (Y_test.shape)
print (Y_train.shape)

print('X_train shape:', X_train.shape)
print('X_train shape:', Y_train.shape )
print('X_train shape:', X_test.shape)
print('X_train shape:', Y_test.shape )

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(Y_train, nb_classes)
Y_test = np_utils.to_categorical(Y_test, nb_classes)

model = Sequential()

model.add(Convolution2D(img_rows, 3, 3, border_mode='same',
                        input_shape=(img_channels, img_rows, img_cols)))
model.add(Activation('relu'))
model.add(Convolution2D(img_rows, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Convolution2D(img_rows*2, 3, 3, border_mode='same'))
model.add(Activation('relu'))
model.add(Convolution2D(img_rows*2, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

# let's train the model using SGD + momentum (how original).
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255


# TRAIN ON BATCHEEEEEEES
validationExamples = int(.2 * len(X_train))
# We reserve the last validationExamples training examples for validation.
X_train, validationArray = X_train[:-validationExamples], X_train[-validationExamples:]
Y_train, validation_labels = Y_train[:-validationExamples], Y_train[-validationExamples:]


if not data_augmentation:
    print('Not using data augmentation.')
    model.fit(X_train, Y_train, batch_size=batch_size,
              nb_epoch=nb_epoch, show_accuracy=True,
              validation_data=(validationArray, validation_labels), shuffle=True)
else:
    print('Using real-time data augmentation.')

    # this will do preprocessing and realtime data augmentation
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

    # compute quantities required for featurewise normalization
    # (std, mean, and principal components if ZCA whitening is applied)
    datagen.fit(X_train)

    # fit the model on the batches generated by datagen.flow()
    model.fit_generator(datagen.flow(X_train, Y_train, batch_size=batch_size),
                        samples_per_epoch=X_train.shape[0],
                        nb_epoch=nb_epoch, show_accuracy=True,
                        validation_data=(validationArray, validation_labels),
                        nb_worker=2)




    score = model.evaluate(X_train, Y_train, show_accuracy=True, verbose=0)
    print('Test score:', score[0])
    print('Test accuracy:', score[1])

    # print ()
    # # third way for batch training
    # for train_batch, labels_batch in datagen.flow(X_train, Y_train):
    #     loss = model.train_on_batch(train_batch, labels_batch)
    #     print (loss)



    # second way of batch training
    #
    # buffer_size = 32
    #
    # for e in range(nb_epoch):
    #     print('-'*40)
    #     print('Epoch', e)
    #     print('-'*40)
    #     print("Training...")
    #     # batch train with realtime data augmentation
    #     progbar = generic_utils.Progbar(X_train.shape[0])
    #     i=0
    #     for X_batch, Y_batch in buffered_gen_threaded(datagen.flow(X_train, Y_train), buffer_size=buffer_size):
    #         print (X_batch.shape)
    #         print (Y_batch.shape)
    #
    #         loss = model.train_on_batch(X_batch, Y_batch)
    #         i=i+1
    #         print (i ,' train loss ', loss)
    #         # progbar.add(X_batch.shape, values=[("train loss", loss)])